### ISSUE TITLE
About evaluation on CommonGen

### ISSUE THREAD

**Issue by bobbyfyb** [VickiCui/MORE#2]
Hi, thanks for your greak job. I just wonder that how you get the evaluation results on CommonGen since their leaderboard of v1.0/v1.1 seems have been archived and are no longer maintained. In your project's data/commongen folder I found that you have uploaded two files of commongen test set: [commongen.test.src_alpha.txt](https://github.com/VickiCui/MORE/blob/main/datas/commongen/commongen.test.src_alpha.txt) and [commongen.test.tgt.txt](https://github.com/VickiCui/MORE/blob/main/datas/commongen/commongen.test.tgt.txt) do the reported MORE's performance in your paper based on these two files?

**Comment by VickiCui** [comment]
您好，您的邮件我已经收到，我会第一时间处理。

**Comment by VickiCui** [comment]
Yes, our test results are based on the two files you mentioned. We obtained these files from the authors of other work, which should correspond to CommonGen v1.0.
